language: php

php:
  - 5.4

before_script:
  - cp app/etc/config.yml-sample app/etc/config.yml
  - php app/www/testenvironment.php

script: phpunit

notifications:
    email:
        - vitaliy@scalr.com
